- name: Go CI
  uses: ghacts/go@v1.0.0
  with:
    project-path: ./src/
    go-version: '1.23.5'
    golang-ci-lint-version: '1.51.0'
    golang-ci-lint-args: '--timeout=5m --disable-all --enable=gofmt --enable=golint'
    skip-lint: false
    skip-build: false
    skip-test: false
